run:
	go run main.go

sol:
	solc --optimize --abi ./contracts/BalanceCheck.sol -o build
	solc --optimize --bin ./contracts/BalanceCheck.sol -o build
	abigen --abi=./build/BalanceCheck.abi --bin=./build/BalanceCheck.bin --pkg=api --out=./api/BalanceCheck.go
